[env:d1_mini]
platform = espressif8266
board = d1_mini
framework = arduino
board_build.filesystem = littlefs
monitor_speed = 115200
upload_speed = 921600

extra_scripts = pre:scripts/version.py

build_flags =
    -DLOG_LEVEL=1

lib_deps =
    tzapu/WiFiManager @ ^2.0.17
    me-no-dev/ESPAsyncWebServer @ ^1.2.3
    me-no-dev/ESPAsyncTCP @ ^1.2.3
    knolleary/PubSubClient @ ^2.8
    bblanchon/ArduinoJson @ ^7.0.0

[env:d1_mini-debug]
extends = env:d1_mini
build_flags =
    -DLOG_LEVEL=3
