; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:d1_mini]
platform = espressif8266
board = d1_mini
framework = arduino
board_build.filesystem = littlefs
monitor_speed = 115200
monitor_dtr = 0
monitor_rts = 0
upload_speed = 921600
extra_scripts = pre:scripts/version.py
build_flags = 
	-DLOG_LEVEL=1
lib_deps = 
	tzapu/WiFiManager @ ^2.0.17
	https://github.com/me-no-dev/ESPAsyncWebServer
	https://github.com/me-no-dev/ESPAsyncTCP
	knolleary/PubSubClient @ ^2.8
	bblanchon/ArduinoJson @ ^7.0.0
platform_packages = platformio/tool-esptoolpy@^2.41100.0

[env:d1_mini-debug]
extends = env:d1_mini
build_flags = 
	-DLOG_LEVEL=3
platform_packages = platformio/tool-esptoolpy@^2.41100.0
